name: Build APK

on:
  workflow_dispatch:     # activador manual
  push:
    branches: [ main ]   # activador automático al hacer push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build APK
        run: |
          echo "Aquí pondrás el comando para compilar tu APK, por ejemplo:"
          # npm install
          # npm run build
